ImageModule: {
  shape: class

  Name: string
  Description: string
  _Label: string
  CachedImage: Image
  LastRunTime: TimeSpan

  Run(Image): Task<Image>

  abstract Process(Image): Image
}

ImageModuleProperties: {
  shape: class
}

ExposureProperties: {
  shape: class

  EV : float
  Bias: float #Camera Bias
}

ExposureProperties -> ImageModuleProperties: Extends {
  target-arrowhead: {
    shape: cf-many
  }
}

Exposure: {
  shape: class
  Properties: ExposureProperties
}

Exposure -> ImageModule: Extends {
  target-arrowhead: {
    shape: cf-many
  }
}

Exposure.Properties -> ExposureProperties: {
  target-arrowhead: {
    shape: cf-many
  }
}


ModuleUserInterface {
    shape : class
    
}